version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: enderecoViacep
       POSTGRES_DB: enderecoViacep
     ports:
       - 5434:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data